// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_upload_prepare from "./routes/api/upload/prepare.ts";
import * as $api_upload_verify from "./routes/api/upload/verify.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $old from "./routes/old.tsx";
import * as $wips_wipcode_ from "./routes/wips/[wipcode].ts";
import * as $UploadWip from "./islands/UploadWip.tsx";
import * as $UploadWip_old from "./islands/UploadWip_old.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/upload/prepare.ts": $api_upload_prepare,
    "./routes/api/upload/verify.ts": $api_upload_verify,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/old.tsx": $old,
    "./routes/wips/[wipcode].ts": $wips_wipcode_,
  },
  islands: {
    "./islands/UploadWip.tsx": $UploadWip,
    "./islands/UploadWip_old.tsx": $UploadWip_old,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
